name: push

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: nabilmerk/rust-grcov
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
            "nightly"
          tag-schedule: |
            "{{date 'YYYYMMDD'}}"
            "nightly"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: false
          file: stretch/Dockerfile
          tags: ${{ steps.docker_meta.outputs.tags }}
      - name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1