name: ci

on:
  schedule:
    - cron: '00 23 * * *' # everyday at 11pm
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:

env:
  DOCKER_IMAGE: localhost:5000/nabilmerk/rust-grcov

jobs:
  multi-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: |
            ${{ env.DOCKER_IMAGE }}
            nabilmerk/rust-grcov
          tag-sha: true

  tag-schedule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag-schedule:
          - ""
          - "cron-{{date 'YYYYMMDD'}}"
          - "{{date 'YYYYMMDD-HHmmss'}}"
          - "schedule"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: |
            ${{ env.DOCKER_IMAGE }}
            nabilmerk/rust-grcov
          tag-sha: true
          tag-schedule: ${{ matrix.tag-schedule }}

  tag-match:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag-match: '\d{1,3}.\d{1,3}.\d{1,3}'
            tag-match-group: '0'
          - tag-match: '\d{1,3}.\d{1,3}'
            tag-match-group: '0'
          - tag-match: 'v(.*)'
            tag-match-group: '1'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: |
            ${{ env.DOCKER_IMAGE }}
            nabilmerk/rust-grcov
          tag-sha: true
          tag-match: ${{ matrix.tag-match }}
          tag-match-group: ${{ matrix.tag-match-group }}

  tag-semver:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag-latest:
          - 'true'
          - 'false'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: |
            ${{ env.DOCKER_IMAGE }}
            nabilmerk/rust-grcov
          tag-semver: |
            {{raw}}
            {{version}}
            {{major}}.{{minor}}.{{patch}}
          tag-latest: ${{ matrix.tag-latest }}

  docker-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tag-sha: true
          tag-semver: |
            v{{version}}
            v{{major}}.{{minor}}
            v{{major}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: stretch/Dockerfile
          tags: ${{ steps.docker_meta.outputs.tags }}
      - name: Inspect image
        run: |
          docker pull ${{ env.DOCKER_IMAGE }}:${{ steps.docker_meta.outputs.version }}
          docker image inspect ${{ env.DOCKER_IMAGE }}:${{ steps.docker_meta.outputs.version }}
      - name: Check manifest
        run: |
          docker buildx imagetools inspect ${{ env.IMAGE }}:${{ steps.docker_meta.outputs.version }}
      - name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: nabilmerk/rust-grcov