name: publish

on:
  schedule:
    - cron: '00 23 * * *' # everyday at 11pm
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: nabilmerk/rust-grcov
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
            "nightly"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v2.4.0
        with:
          push: true
          file: stretch/Dockerfile
          tags: ${{ steps.docker_meta.outputs.tags }}
      - name: Inspect image
        run: |
          docker pull nabilmerk/rust-grcov:${{ steps.docker_meta.outputs.version }}
          docker image inspect nabilmerk/rust-grcov:${{ steps.docker_meta.outputs.version }}
      - name: Check manifest
        run: |
          docker buildx imagetools inspect nabilmerk/rust-grcov:${{ steps.docker_meta.outputs.version }}
      - name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: nabilmerk/rust-grcov