name: push

on: [push, pull_request]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        if: startsWith(github.ref, 'refs/tags') == false
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v3.6.2
        with:
          images: nabilmerk/rust-grcov
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
            "nightly"
          tag-schedule: |
            "{{date 'YYYYMMDD'}}"
            "nightly"
      - name: Set up Docker Buildx
        if: startsWith(github.ref, 'refs/tags') == false
        uses: docker/setup-buildx-action@v1
      - name: Build and push image
        if: startsWith(github.ref, 'refs/tags') == false
        uses: docker/build-push-action@v2
        with:
          push: false
          file: stretch/Dockerfile
          tags: ${{ steps.docker_meta.outputs.tags }}
      - name: Dump context
        if: startsWith(github.ref, 'refs/tags') == false
        uses: crazy-max/ghaction-dump-context@v1