name: ci

on:
  schedule:
    - cron: '00 23 * * *' # everyday at 11pm
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  docker-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag-schedule:
          - ""
          - "cron-{{date 'YYYYMMDD'}}"
          - "{{date 'YYYYMMDD-HHmmss'}}"
          - "schedule"
        tag-latest:
          - 'true'
          - 'false'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: name/app
          tag-sha: true
          tag-semver: |
            v{{version}}
            v{{major}}.{{minor}}
            v{{major}}
          tag-latest: ${{ matrix.tag-latest }}
          tag-schedule: ${{ matrix.tag-schedule }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: stretch/Dockerfile
          tags: ${{ steps.docker_meta.outputs.tags }}
      - name: Check manifest
        run: |
          docker buildx imagetools inspect rust-grcov:${{ steps.docker_meta.outputs.version }}
      - name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/rust-grcov